name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Restore Api packages
      run: dotnet restore Src/Web/TaskManager.Api
    - name: Restore Application packages
      run: dotnet restore Src/Web/TaskManager.Application
    - name: Restore Domain packages
      run: dotnet restore Src/Web/TaskManager.Domain
    - name: Restore Infrastructure packages
      run: dotnet restore Src/Web/TaskManager.Infrastructure
    - name: Restore Persistence packages
      run: dotnet restore Src/Web/TaskManager.Persistence
    - name: Build Api
      run: dotnet build Src/Web/TaskManager.Api
    - name: Build Application
      run: dotnet build Src/Web/TaskManager.Application
    - name: Build Domain
      run: dotnet build Src/Web/TaskManager.Domain
    - name: Build Infrastructure
      run: dotnet build Src/Web/TaskManager.Infrastructure
    - name: Build Persistence
      run: dotnet build Src/Web/TaskManager.Persistence
    - name: Run Web Tests
      run: dotnet test Src/Tests/TaskManager.Tests.Web
    - name: Run Functional Tests
      run: dotnet test Src/Tests/TaskManager.Tests.WebFunctional
